// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `convert`
// These types are ignored because they are not used by any `pub` functions: `VntApiCallbackInner`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `connect`, `create_tun`, `error`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `handshake`, `peer_client_list`, `register`, `stop`, `success`

Future<VntApi> vntInit(
        {required VntConfig vntConfig, required VntApiCallback call}) =>
    RustLib.instance.api
        .crateApiVntApiVntInit(vntConfig: vntConfig, call: call);

/// 初始化日志系统，支持所有平台
/// log_dir: 日志目录路径，例如 "logs" 或 "/data/data/app/logs"
/// config_path: 持久化配置文件路径（用于打印到日志）
void initLogWithPath({required String logDir, required String configPath}) =>
    RustLib.instance.api.crateApiVntApiInitLogWithPath(logDir: logDir, configPath: configPath);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VntApi>>
abstract class VntApi implements RustOpaqueInterface {
  RustCurrentDeviceInfo currentDevice();

  Future<List<RustPeerClientInfo>> deviceList();

  String downStream();

  Uint64List downStreamLine({required String ip});

  String ipDownStreamTotal({required String ip});

  String ipUpStreamTotal({required String ip});

  bool isStopped();

  RustNatInfo natInfo();

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<VntApi> newInstance(
          {required VntConfig vntConfig, required VntApiCallback call}) =>
      RustLib.instance.api
          .crateApiVntApiVntApiNew(vntConfig: vntConfig, call: call);

  RustNatInfo? peerNatInfo({required String ip});

  RustRoute? route({required String ip});

  List<(String, List<RustRoute>)> routeList();

  void stop();

  List<(String, BigInt, BigInt)> streamAll();

  String upStream();

  Uint64List upStreamLine({required String ip});
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<VntApiCallback>>
abstract class VntApiCallback implements RustOpaqueInterface {
  factory VntApiCallback(
          {required FutureOr<void> Function() successFn,
          required FutureOr<void> Function(RustDeviceInfo) createTunFn,
          required FutureOr<void> Function(RustConnectInfo) connectFn,
          required FutureOr<bool> Function(RustHandshakeInfo) handshakeFn,
          required FutureOr<bool> Function(RustRegisterInfo) registerFn,
          required FutureOr<int> Function(RustDeviceConfig) generateTunFn,
          required FutureOr<void> Function(List<RustPeerClientInfo>)
              peerClientListFn,
          required FutureOr<void> Function(RustErrorInfo) errorFn,
          required FutureOr<void> Function() stopFn}) =>
      RustLib.instance.api.crateApiVntApiVntApiCallbackNew(
          successFn: successFn,
          createTunFn: createTunFn,
          connectFn: connectFn,
          handshakeFn: handshakeFn,
          registerFn: registerFn,
          generateTunFn: generateTunFn,
          peerClientListFn: peerClientListFn,
          errorFn: errorFn,
          stopFn: stopFn);
}

class RustConnectInfo {
  final BigInt count;
  final String address;

  const RustConnectInfo({
    required this.count,
    required this.address,
  });

  @override
  int get hashCode => count.hashCode ^ address.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustConnectInfo &&
          runtimeType == other.runtimeType &&
          count == other.count &&
          address == other.address;
}

class RustCurrentDeviceInfo {
  final String virtualIp;
  final String virtualNetmask;
  final String virtualGateway;
  final String virtualNetwork;
  final String broadcastIp;
  final String connectServer;
  final String status;

  const RustCurrentDeviceInfo({
    required this.virtualIp,
    required this.virtualNetmask,
    required this.virtualGateway,
    required this.virtualNetwork,
    required this.broadcastIp,
    required this.connectServer,
    required this.status,
  });

  @override
  int get hashCode =>
      virtualIp.hashCode ^
      virtualNetmask.hashCode ^
      virtualGateway.hashCode ^
      virtualNetwork.hashCode ^
      broadcastIp.hashCode ^
      connectServer.hashCode ^
      status.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustCurrentDeviceInfo &&
          runtimeType == other.runtimeType &&
          virtualIp == other.virtualIp &&
          virtualNetmask == other.virtualNetmask &&
          virtualGateway == other.virtualGateway &&
          virtualNetwork == other.virtualNetwork &&
          broadcastIp == other.broadcastIp &&
          connectServer == other.connectServer &&
          status == other.status;
}

class RustDeviceConfig {
  final String virtualIp;
  final String virtualNetmask;
  final String virtualGateway;
  final String virtualNetwork;
  final List<(String, String)> externalRoute;

  const RustDeviceConfig({
    required this.virtualIp,
    required this.virtualNetmask,
    required this.virtualGateway,
    required this.virtualNetwork,
    required this.externalRoute,
  });

  @override
  int get hashCode =>
      virtualIp.hashCode ^
      virtualNetmask.hashCode ^
      virtualGateway.hashCode ^
      virtualNetwork.hashCode ^
      externalRoute.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDeviceConfig &&
          runtimeType == other.runtimeType &&
          virtualIp == other.virtualIp &&
          virtualNetmask == other.virtualNetmask &&
          virtualGateway == other.virtualGateway &&
          virtualNetwork == other.virtualNetwork &&
          externalRoute == other.externalRoute;
}

class RustDeviceInfo {
  final String name;
  final String version;

  const RustDeviceInfo({
    required this.name,
    required this.version,
  });

  @override
  int get hashCode => name.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustDeviceInfo &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          version == other.version;
}

class RustErrorInfo {
  final RustErrorType code;
  final int? serverCode;
  final String? msg;

  const RustErrorInfo({
    required this.code,
    this.serverCode,
    this.msg,
  });

  @override
  int get hashCode => code.hashCode ^ serverCode.hashCode ^ msg.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustErrorInfo &&
          runtimeType == other.runtimeType &&
          code == other.code &&
          serverCode == other.serverCode &&
          msg == other.msg;
}

enum RustErrorType {
  tokenError,
  disconnect,
  addressExhausted,
  ipAlreadyExists,
  invalidIp,
  localIpExists,
  failedToCreateDevice,
  networkError,
  unknown,
  passwordError,
  ;
}

class RustHandshakeInfo {
  final String? finger;
  final String version;

  const RustHandshakeInfo({
    this.finger,
    required this.version,
  });

  @override
  int get hashCode => finger.hashCode ^ version.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustHandshakeInfo &&
          runtimeType == other.runtimeType &&
          finger == other.finger &&
          version == other.version;
}

class RustNatInfo {
  final List<String> publicIps;
  final String natType;
  final String? localIpv4;
  final String? ipv6;

  const RustNatInfo({
    required this.publicIps,
    required this.natType,
    this.localIpv4,
    this.ipv6,
  });

  @override
  int get hashCode =>
      publicIps.hashCode ^
      natType.hashCode ^
      localIpv4.hashCode ^
      ipv6.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustNatInfo &&
          runtimeType == other.runtimeType &&
          publicIps == other.publicIps &&
          natType == other.natType &&
          localIpv4 == other.localIpv4 &&
          ipv6 == other.ipv6;
}

class RustPeerClientInfo {
  final String virtualIp;
  final String name;
  final String status;
  final bool clientSecret;

  const RustPeerClientInfo({
    required this.virtualIp,
    required this.name,
    required this.status,
    required this.clientSecret,
  });

  @override
  int get hashCode =>
      virtualIp.hashCode ^
      name.hashCode ^
      status.hashCode ^
      clientSecret.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustPeerClientInfo &&
          runtimeType == other.runtimeType &&
          virtualIp == other.virtualIp &&
          name == other.name &&
          status == other.status &&
          clientSecret == other.clientSecret;
}

class RustRegisterInfo {
  final String virtualIp;
  final String virtualNetmask;
  final String virtualGateway;

  const RustRegisterInfo({
    required this.virtualIp,
    required this.virtualNetmask,
    required this.virtualGateway,
  });

  @override
  int get hashCode =>
      virtualIp.hashCode ^ virtualNetmask.hashCode ^ virtualGateway.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRegisterInfo &&
          runtimeType == other.runtimeType &&
          virtualIp == other.virtualIp &&
          virtualNetmask == other.virtualNetmask &&
          virtualGateway == other.virtualGateway;
}

class RustRoute {
  final String protocol;
  final String addr;
  final int metric;
  final PlatformInt64 rt;

  const RustRoute({
    required this.protocol,
    required this.addr,
    required this.metric,
    required this.rt,
  });

  @override
  int get hashCode =>
      protocol.hashCode ^ addr.hashCode ^ metric.hashCode ^ rt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is RustRoute &&
          runtimeType == other.runtimeType &&
          protocol == other.protocol &&
          addr == other.addr &&
          metric == other.metric &&
          rt == other.rt;
}

class VntConfig {
  final List<String> serverAddr;
  final String certMode;
  final String networkCode;
  final String deviceId;
  final String deviceName;
  final String? tunName;
  final String? ip;
  final String? password;
  final bool noPunch;
  final bool compress;
  final bool rtx;
  final bool fec;
  final List<String> input;
  final List<String> output;
  final bool noNat;
  final bool noTun;
  final int? mtu;
  final List<String> portMapping;
  final bool allowPortMapping;
  final List<String> udpStun;
  final List<String> tcpStun;
  final int? tunnelPort;

  const VntConfig({
    required this.serverAddr,
    required this.certMode,
    required this.networkCode,
    required this.deviceId,
    required this.deviceName,
    this.tunName,
    this.ip,
    this.password,
    required this.noPunch,
    required this.compress,
    required this.rtx,
    required this.fec,
    required this.input,
    required this.output,
    required this.noNat,
    required this.noTun,
    this.mtu,
    required this.portMapping,
    required this.allowPortMapping,
    required this.udpStun,
    required this.tcpStun,
    this.tunnelPort,
  });

  @override
  int get hashCode =>
      serverAddr.hashCode ^
      certMode.hashCode ^
      networkCode.hashCode ^
      deviceId.hashCode ^
      deviceName.hashCode ^
      tunName.hashCode ^
      ip.hashCode ^
      password.hashCode ^
      noPunch.hashCode ^
      compress.hashCode ^
      rtx.hashCode ^
      fec.hashCode ^
      input.hashCode ^
      output.hashCode ^
      noNat.hashCode ^
      noTun.hashCode ^
      mtu.hashCode ^
      portMapping.hashCode ^
      allowPortMapping.hashCode ^
      udpStun.hashCode ^
      tcpStun.hashCode ^
      tunnelPort.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is VntConfig &&
          runtimeType == other.runtimeType &&
          serverAddr == other.serverAddr &&
          certMode == other.certMode &&
          networkCode == other.networkCode &&
          deviceId == other.deviceId &&
          deviceName == other.deviceName &&
          tunName == other.tunName &&
          ip == other.ip &&
          password == other.password &&
          noPunch == other.noPunch &&
          compress == other.compress &&
          rtx == other.rtx &&
          fec == other.fec &&
          input == other.input &&
          output == other.output &&
          noNat == other.noNat &&
          noTun == other.noTun &&
          mtu == other.mtu &&
          portMapping == other.portMapping &&
          allowPortMapping == other.allowPortMapping &&
          udpStun == other.udpStun &&
          tcpStun == other.tcpStun &&
          tunnelPort == other.tunnelPort;
}
